# Generated by Django 4.0.2 on 2022-03-30 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_product_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='measure',
            field=models.CharField(choices=[('units', 'Units'), ('kg', 'Kilograms'), ('l', 'Liters')], default=('units', 'Units'), max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
