# Generated by Django 4.0.2 on 2022-03-13 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_info_product_description_alter_picture_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='quantity',
            new_name='price',
        ),
    ]
