# Generated by Django 4.0.2 on 2022-03-30 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_product_measure_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='measure',
            field=models.CharField(choices=[('units', 'Units'), ('kg', 'Kilograms'), ('l', 'Liters')], max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
