# Generated by Django 4.0.2 on 2022-03-17 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_quantity_bid_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(default='New', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='initial_bid',
            field=models.DecimalField(decimal_places=2, default=3, max_digits=8),
        ),
    ]
