# Generated by Django 4.0.2 on 2022-03-17 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_product_condition_product_initial_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='condition',
        ),
        migrations.AddField(
            model_name='product',
            name='origin',
            field=models.CharField(default='Spain', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='initial_bid',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
