# Generated by Django 4.0.2 on 2022-03-17 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_product_condition_product_origin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='origin',
            field=models.CharField(max_length=30),
        ),
    ]
